/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f446xx.h"


void button_init(void);
void uart2_init(void);
void dma1_init(void);


int main(void)
{
	button_init();
	uart2_init();
	dma1_init();

	while(1);
	return 0;
}

void button_init(void)
{
	//User button at PC13

	//1. Enable GPIOC peripheral clock
	RCC->AHB1ENR |= (1 << 2);

	//2.GPIO pin in input mode
	GPIOC->MODER &= ~(3 << 26);

	//3.Enable the interrupt over that GPIO pin
	EXTI->IMR |= (1 << 13);

	//4.Enabling SYSCFG Clock
	RCC->APB2ENR |= (1 << 14);

	//5.Select PC13 for EXTI13
	SYSCFG->EXTICR[3] &= ~(0xF << 4);
	SYSCFG->EXTICR[3] |=  (0x2 << 4);

	//6. Configure the edge detection on the GPIO pin
	EXTI->FTSR |= (1 << 13);

	//7.Enable the IRQ for the GPIO in NVIC
	NVIC->ISER[1] |= (1 << 8);
}

void uart2_init(void)
{

}

void dma1_init(void)
{

}

